### ISSUE TITLE
Allow loading and caching of custom blocklist

### ISSUE THREAD

**Issue by fdebijl** [Fdebijl/FakeNewsBlocker#4]
Caching should also apply to regular blocklist.

**Comment by fdebijl** [comment]
Caching added with fa9e57fc2ffa34a514aee833715bd6b0615d8a61 - option for custom blocklist is on roadmap for 1.3

**Comment by Fdebijl** [comment]
Added in 80ee5c352836b4932b82fe642d2fc4cb47868696

**Comment by fdebijl** [comment]
Added in 80ee5c352836b4932b82fe642d2fc4cb47868696
